nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Mash-Art-Graphic API
            description: Description de votre API
            version: 1.0.0
